### ISSUE TITLE
MineTime keeps asking for calendar creation on startup even if there are several set up

### ISSUE THREAD

**Issue by flg** [marcoancona/MineTime#70]
Starting from version 1.4.0, MineTime me to add calendars on startup, not systematically though, whereas two calendars are configured and showing up in the back of the Add calendar window. I also noticed that each time it does that, the color theme is changed back to light (I use the dark theme).

There is no way to bypass this add calendar step. So I need to re-add an existing calendar.

**Comment by marcoancona** [comment]
Thanks for your notice. Does the problem persists also with the latest version (1.4.1)?

**Comment by flg** [comment]
I haven't seen this issue for the version 1.4.1.

**Comment by marcoancona** [comment]
This annoying bug should have been solved already in 1.4.0 (that was replaced by 1.4.1 less than 24 hours after). If the problem appears again, do not hesitate to ping me.

**Comment by flg** [comment]
It happened again; this time while the application was running. The modal window "Welcome to MineTime" appears, aking to validate EULA and privacy policy. When I accept it, it asks for a calendar creation. In the background the application (grayed out) still shows the configured calendars and looks as usual.

I see in the background that MineTime announces the new version (1.4.2) and I wonder if it is related. I remember having the same problem with 1.4.0 at the time 1.4.1 was released. Not 100% sure though.

Let me know if I can help with more information.

**Comment by marcoancona** [comment]
Thanks for pointing out! So, if I understand correctly, you did not update (yet) to 1.4.2, is it correct? But you see the update button.

**Comment by marcoancona** [comment]
What operating system are you using?

**Comment by flg** [comment]
Correct. And yes I see the update button. I am running it on Linux (CentOS 7.5 and Ubuntu 18.04 both up to date). I am waiting to see if you need more info before upgrading to 1.4.2.

**Comment by marcoancona** [comment]
Did you get the screen on both systems?

**Comment by flg** [comment]
I just started the Ubuntu. It now shows the update button (to 1.4.2) and the modal "Welcome" window still hasn't showed up. I will let it run to see if it appears at some point.

**Comment by flg** [comment]
This problem is back. Version 1.4.5. I updated on the day of the release, so some days ago now. Minetime is running since Monday without interruption and this morning it shows the "Welcome to Minetime". I accept the license and it asks for calendar connection. My calendars still show in the background. I tried to restart the application at this point: it comes back with the same "Welcome" panel and the theme is back to "light" (it was dark).

As this keeps happening, it would be nice to have a button to skip the calendar add/deletion step.
